title: Skills Registry
description: Discover and install skills for AI agents.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: null

collections:
  skills:
    output: true
    permalink: /:author/:repo/:title/
